from typing import Sequence

import numpy as np

DEFAULT_SQUARE_GROUP_SIZE = 3
DEFAULT_SQUARE_GROUP_SHAPE = (DEFAULT_SQUARE_GROUP_SIZE, DEFAULT_SQUARE_GROUP_SIZE)
DEFAULT_SUDOKU_SIZE = DEFAULT_SQUARE_GROUP_SIZE ** 2

